# Build settings
markdown: kramdown
highlighter: rouge

# Site settings
title: "Food & Drink"
description: > # this means to ignore newlines until "email:"

email: mail@audreywatters.com
#blog logo
logo: "/assets/images/new_hack_logo.jpg"
logo2: "/assets/images/hack.png"
# blog cover
cover: "/assets/images/grocery-store-mafia.jpg"
covercredits: "http://bryanmmathers.com/"

name: 'Audrey Watters'
author: 'Audrey Watters'
author_image: "/assets/images/author.jpg"

paginate:	10
paginate_path: "/blog/page:num"
permalink: /:categories/:year/:month/:day/:title 

url: "http://food.audreywatters.com" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@audreywatters'

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/audreywatters
    desc: Follow me on twitter

  - icon:	facebook
    url:	https://facebook.com/audreywatters
    desc: Like me on facebook

  - icon:	github
    url:	https://github.com/audreywatters/food
    desc: Fork me on github

  - icon: rss
    url:  http://food.audreywatters.com/feed.xml
    desc: Subscribe

  - icon: envelope
    url:  mailto:mail@audreywatters.com
    desc: Email  
  
# Gems
plugins: [jekyll-paginate]